import type { ResolvedProduct } from "./generated/ResolvedProduct";
import {
  LOCAL_POSTGRES,
  buildCommand,
  dbNameOf,
  linkedGearsCommand,
  plainPath,
  runCommand,
  runTargetsOf,
  toolchainVerdict,
  urlOf,
  withPostgres,
} from "./run-product";

/** `config/shop.yaml` as the engine generated it for the product `shop` (2026-09-29 run). */
const SHOP_YAML = `# GENERATED by gearbox 0.1.0 -- do not edit. Run \`gearbox generate\` to regenerate.

server:
  home_dir: ~/.cf-gears/shop/dev
gears:
  account-management:
    config: {}
  api-gateway:
    config:
      bind_addr: 127.0.0.1:8087
  authn-resolver:
    config: {}
  authz-resolver:
    config: {}
  bss-pricing:
    config: {}
  gear-orchestrator:
    config: {}
  grpc-hub:
    config:
      listen_addr: 127.0.0.1:50051
  resource-group:
    config: {}
  tenant-resolver:
    config: {}
  types-registry:
    config: {}
`;

const DB_GEARS = ["account-management", "bss-pricing", "resource-group", "types-registry"];

function shop(): ResolvedProduct {
  return {
    applications: [
      {
        name: "shop",
        kind: "host",
        anchor: "api-gateway",
        gears: ["account-management", "api-gateway", "bss-pricing", "grpc-hub", "resource-group", "types-registry"],
        replicas: 1,
        entrypoint: "run_server",
        bin_name: "gbx-shop",
        crate_name: "gbx-shop",
        listens: [
          { name: "grpc", gear: "grpc-hub", config_key: "listen_addr", address: "127.0.0.1:50051", allow_loopback_advertise: true },
          { name: "rest", gear: "api-gateway", config_key: "bind_addr", address: "127.0.0.1:8087", allow_loopback_advertise: true },
        ],
        rest_host: "api-gateway",
        needs_db: true,
      },
      {
        name: "worker",
        kind: "worker",
        anchor: "bss-pricing",
        gears: ["bss-pricing"],
        replicas: 1,
        entrypoint: "run_oop_with_options",
        bin_name: "gbx-worker",
        crate_name: "gbx-worker",
        needs_db: true,
      },
    ],
  } as unknown as ResolvedProduct;
}

describe("what Run can start", () => {
  const hasDb = (gear: string): boolean => DB_GEARS.includes(gear);

  it("offers the host applications, not the workers they spawn", () => {
    expect(runTargetsOf(shop(), hasDb).map((t) => t.app)).toEqual(["shop"]);
  });

  it("names the binary, the generated config, Studio's copy and the gears that need a database", () => {
    const [target] = runTargetsOf(shop(), hasDb);
    expect(target).toEqual({
      app: "shop",
      bin: "gbx-shop",
      config: "config/shop.yaml",
      localConfig: "config/shop.local.yaml",
      dbGears: ["account-management", "bss-pricing", "resource-group", "types-registry"],
      address: "127.0.0.1:8087",
    });
  });

  it("asks for no database when the application needs none", () => {
    const product = shop();
    (product.applications[0] as { needs_db: boolean }).needs_db = false;
    expect(runTargetsOf(product, hasDb)[0]?.dbGears).toEqual([]);
  });

  it("runs the binary the way its main.rs parses: --config before the subcommand", () => {
    const [target] = runTargetsOf(shop(), hasDb);
    expect(buildCommand(target!)).toBe("cargo build --bin gbx-shop");
    expect(runCommand(target!, "config/shop.local.yaml")).toBe("cargo run --bin gbx-shop -- --config config/shop.local.yaml run");
    expect(linkedGearsCommand(target!)).toBe("cargo run --bin gbx-shop -- --list-registered-gears");
  });
});

describe("the address and the paths", () => {
  it("opens a wildcard bind on loopback", () => {
    expect(urlOf("127.0.0.1:8087")).toBe("http://127.0.0.1:8087");
    expect(urlOf("0.0.0.0:8087")).toBe("http://127.0.0.1:8087");
  });

  it("drops the Windows verbatim prefix for the terminal's folder", () => {
    expect(plainPath("\\\\?\\C:\\w\\.gearbox\\shop\\dev")).toBe("C:\\w\\.gearbox\\shop\\dev");
    expect(plainPath("/w/.gearbox/shop/dev")).toBe("/w/.gearbox/shop/dev");
  });

  it("drops it in the forward-slash form the engine reports too", () => {
    expect(plainPath("//?/C:/w/gears/new-gear")).toBe("C:/w/gears/new-gear");
    expect(plainPath("//?/UNC/host/share/gears")).toBe("//host/share/gears");
  });

  it("names a gear's database after the gear", () => {
    expect(dbNameOf("account-management")).toBe("account_management");
  });
});

describe("the database section generate leaves out", () => {
  it("adds a Postgres server and one database per gear, as the run that worked had them", () => {
    const added = withPostgres(SHOP_YAML, DB_GEARS);
    expect(added?.missing).toEqual([]);
    const text = added?.text ?? "";
    expect(text).toContain(
      [
        "database:",
        "  servers:",
        "    pg:",
        '      engine: "postgres"',
        '      host: "127.0.0.1"',
        "      port: 5432",
        '      user: "postgres"',
        '      password: "${GEARS_PG_PASSWORD}"',
        "      params:",
        '        sslmode: "disable"',
        "gears:",
      ].join("\n"),
    );
    expect(text).toContain('  resource-group:\n    database: { server: "pg", dbname: "resource_group" }\n    config: {}');
    expect(text).toContain('  account-management:\n    database: { server: "pg", dbname: "account_management" }\n    config: {}');
    expect(text).toContain("  api-gateway:\n    config:\n      bind_addr: 127.0.0.1:8087");
    expect(text).not.toContain('dbname: "api_gateway"');
  });

  it("leaves every other line as the engine wrote it", () => {
    const lines = (withPostgres(SHOP_YAML, DB_GEARS)?.text ?? "").split("\n");
    const block = lines.indexOf("database:");
    const gears = lines.indexOf("gears:");
    const without = [...lines.slice(0, block), ...lines.slice(gears)].filter((line) => !line.startsWith("    database: "));
    expect(gears - block).toBe(10);
    expect(without.join("\n")).toBe(SHOP_YAML);
  });

  it("does nothing to a configuration that already has a database section", () => {
    const once = withPostgres(SHOP_YAML, DB_GEARS)?.text ?? "";
    expect(withPostgres(once, DB_GEARS)).toBeUndefined();
  });

  it("names a gear it cannot find instead of guessing", () => {
    expect(withPostgres(SHOP_YAML, ["no-such-gear", "bss-pricing"])?.missing).toEqual(["no-such-gear"]);
  });

  it("uses the server the member configured", () => {
    const text = withPostgres(SHOP_YAML, ["bss-pricing"], { ...LOCAL_POSTGRES, host: "db.local", port: 6543, passwordEnv: "PG_PW" })?.text ?? "";
    expect(text).toContain('host: "db.local"');
    expect(text).toContain("port: 6543");
    expect(text).toContain('password: "${PG_PW}"');
  });
});

describe("whether Build and Run can be offered", () => {
  const found = { cargo: "cargo 1.97.0", msvcLinker: "n/a" as const, docker: true, pgPasswordSet: false };

  it("offers them with cargo and a linker", () => {
    expect(toolchainVerdict(found)).toEqual({ ready: true });
    expect(toolchainVerdict({ ...found, msvcLinker: "found" })).toEqual({ ready: true });
  });

  it("says cargo is missing, with rustup, rather than failing in a terminal", () => {
    const verdict = toolchainVerdict({ ...found, cargo: undefined });
    expect(verdict.ready).toBe(false);
    expect(verdict.reason).toMatch(/cargo/);
    expect(verdict.help?.url).toBe("https://rustup.rs");
  });

  it("says the MSVC linker is missing on Windows", () => {
    const verdict = toolchainVerdict({ ...found, msvcLinker: "missing" });
    expect(verdict.ready).toBe(false);
    expect(verdict.reason).toMatch(/link\.exe/);
    expect(verdict.help?.url).toMatch(/visual-cpp-build-tools/);
  });
});
